name: "🐞 Bug"
description: "버그가 발생했어요."
title: "OO 버그 해결"
labels: "🍀 BE, 🐛 fix"
body:
  - type: checkboxes
    attributes:
      label: 📋 Checklist
      description: 반드시 먼저 체크해주세요!
      options:
        - label: 📁 Jira에 이슈를 등록했나요?
  - type: textarea
    attributes:
      label: 🐞 Problem
      description: 현재 발생한 문제에 대해 설명해주세요.
      placeholder: 리스트 형태로 적어주세요!
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🌱 Expected Result
      description: 정상 동작일 때의 결과를 설명해주세요.
      placeholder: 리스트 형태로 적어주세요!
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🙋🏻 More
      description: 관련된 Discussion 등이 있다면 첨부해주세요.
      placeholder: 리스트 형태로 적어주세요!
