name: "✨ Feature"
description: "새로운 기능이 필요해요."
title: "OO 기능 구현"
labels: "🍀 BE, ✨ feature"
body:
  - type: checkboxes
    attributes:
      label: 📋 Checklist
      description: 반드시 먼저 체크해주세요!
      options:
        - label: 📁 Jira에 이슈를 등록했나요?
  - type: textarea
    attributes:
      label: ✅ Tasks
      description: 해야 하는 일에 대한 Tasks를 작성해주세요.
      placeholder: 체크 박스 형태로 적어주세요!
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🙋🏻 More
      description: 관련된 Discussion 등이 있다면 첨부해주세요.
      placeholder: 리스트 형태로 적어주세요!
